### ISSUE TITLE
How to change filename before upload starts?

### ISSUE THREAD

**Issue by Obvio** [rico345100/socket.io-file#1]
Thanks for this!

I wanted to know if it's possible to change the uploaded file name before it writes to the server, i want to always allow uploads with `{overwrite:false}`.

Thanks again!

**Comment by rico345100** [comment]
Hello, @Obvio!
I just added new option "rename" which can change the file name before upload starts!

```javascript
var count = 0;
var uploader = new SocketIOFile(socket, {
	overwrite: false
	rename: function(filename) {
		var split = filename.split('.');	// split filename by .(extension)
		var fname = split[0];	// filename without extension
		var ext = split[1];

		return `${fname}_${count++}.${ext}`;
	}
});
```

You can now change the file name using 'rename' option, returning value will be the name of a file. Enjoy ;)

Oh, don't forget to update socket.io-file to 2.0.1 !

**Comment by Obvio** [comment]
thanks! works great!
by the way, it might be better using
```javascript
var path = require('path');
...
rename: function(filename) {
        var fname = path.parse(filename).name;
        var ext = path.parse(filename).ext;
	return `${fname}_${count++}.${ext}`;
}
```
because a file name can have `.` in it.

**Comment by rico345100** [comment]
@Obvio Nice point :) I will change the example in document later, thanks! Anyway If you like this module, don't forget to give me a star!
