### ISSUE TITLE
Can I use this library when the interface API want fs.readFile?

### ISSUE THREAD

**Issue by lborgman** [rico345100/socket.io-file#15]
Please see my question here:

https://stackoverflow.com/questions/49783403/can-i-use-fs-readfile-instead-of-fs-readfilesync-can-i-use-a-socket-stream-inst

Please note that I want to upload big files (and avoid having them in memory).

**Comment by rico345100** [comment]
Sorry, I don't know what you are talking to.

**Comment by lborgman** [comment]
I simply did not know anything about what abstraction level the sockets and pipes etc are on in Node.js. But since no one did understand what I asked my conclusion is that there are nothing like handshake etc for those interfaces.

I asked here because such ideas perhaps was recognized here.

But I think I know what I can expect to find now, thanks.
