### ISSUE TITLE
Upload Fails in the meddile without triggering the Error event.

### ISSUE THREAD

**Issue by MeddahAbdellah** [rico345100/socket.io-file#20]
I am trying to upload file from client to server, I am using exactly the same codes as the documentation, the problem is that the upload fails, and I get "Socket connected" which I understand from the client was disconnected and connected to the socket, but the error event doesn't trigger and it is possible to resume uploading after disconnect ?

**Comment by rico345100** [comment]
Could you explain more details about "upload fails"? How doesn't it work? Also you can't resume the transmission if you disconnected.

**Comment by rico345100** [comment]
Did you solve the problem? Can I close this issue?

**Comment by rico345100** [comment]
Closing this issue because you didn't responded. You can freely re-open if you needed.
