### ISSUE TITLE
Get the original file name when using rename

### ISSUE THREAD

**Issue by banv** [rico345100/socket.io-file#21]
I've set rename function to generate unique file name when upload file, but I also want to get the original file name to store in my database. 
But on "complete" event, fileInfo object haven't original file name.
Can you put original file name into fileInfo object? 
Thank you!

**Comment by rico345100** [comment]
Sure, I will check the code after get back to home.

**Comment by banv** [comment]
Thank you for your feedback! I've created a pull request #22 , please review it.

**Comment by rico345100** [comment]
Hey, I just get home but I need to some test about changes. Unfortunately, I have a something todo before that. I will do the test and publish the package as fast as I possible. Oh, also I renamed emitObj.oname to emitObj.originalFileName to make variable more understandable! You can check my commit here: https://github.com/rico345100/socket.io-file/commit/9c32bc8f527dd55ba0f7547fe7df29c609f42e59

**Comment by rico345100** [comment]
Package published! Please close this issue when you check the new version!

**Comment by banv** [comment]
I've checked new version, now I can use fileInfo.originalFileName in my project. Thank you so much!
