### ISSUE TITLE
Solution for File Download through this package?

### ISSUE THREAD

**Issue by BunnyMan1** [rico345100/socket.io-file#23]
I have successfully used this package for uploading files through web sockets from React frontend to Node backend. Everything works fine. I want to download files the same way through web sockets for a Chat application. Is there any way that i'm missing here to download the files? Thank you.

**Comment by rico345100** [comment]
Unfortunately there's no download feature in here. You could just use HTTP instead. However that could be interesting, I will consider to add to next feature.

**Comment by rico345100** [comment]
I added a milestone to support this feature. I will let you know when it's done.

**Comment by BunnyMan1** [comment]
Thank you for the response. Good package by the way. It helped me avoid the ArrayBuffer implementation.
