### ISSUE TITLE
Can't resolve fs with webpack

### ISSUE THREAD

**Issue by benoitlahoz** [rico345100/socket.io-file#28]
While importing from a Vue.js component (compiled by Webpack) have this issue: 

Error: Can't resolve 'fs' in '/blablabla/node_modules/mime'
Error: Can't resolve 'fs' in '/blablabla/node_modules/socket.io-file' (twice)

Only trying to
`import SocketIOFileClient from 'socket.io-file'`

**Comment by rico345100** [comment]
You should import client module, not this one.
