### ISSUE TITLE
Infinite loop of streaming 0 bytes

### ISSUE THREAD

**Issue by jfmmm** [rico345100/socket.io-file#3]
Hi,

I'm having an issue with this and was wondering if you had any idea what might be the issue.

I tryed the exemple you made and everything work fine, but then I installed this on the site I'm working on and now I have an infinite loop when I try to upload a file.

It's clearly connecting to the backend since it log the file name correctly but it just try to send the file in a loop while never actually sending anything.

In the front I get a single log of the file:

```
Start uploading
{
name :"Gabarie Cross Reference Guide.xlsx"
size: 126720
uploadTo: ""
}
```

then it just log `Streaming... sent 0 bytes.` in a loop to infinity.

in the back I get pretty much the same thing :

```
Start uploading
{ name: 'Gabarie Cross Reference Guide.xlsx',
  size: 126720,
  uploadDir: 'data/Gabarie Cross Reference Guide.xlsx' }
0 / 126720 byte(s)
0 / 126720 byte(s)
0 / 126720 byte(s)
0 / 126720 byte(s)
0 / 126720 byte(s)
0 / 126720 byte(s)
0 / 126720 byte(s)
```

It also create the file with the right name in the data folder but it stay at 0 bytes in size.

So the socketio connections is clearly happening but not much else.

I checked my code 4 times and I'm pretty sure it's the same, the only difference was that I was using .connect but I tryed it your way and it change nothing.

`Socketio.connect(this.get('serverUrl'));`

instead of

`Socketio(this.get('serverUrl'));`

Thanks.

**Comment by jfmmm** [comment]
I changed your demo to use my backend and it work fine, so it must be something in the front of my app 😕

**Comment by rico345100** [comment]
Ok, looks like it's not issue about this module. I'm closing this, thanks!

**Comment by jfmmm** [comment]
The problem was that I was initializing the thing at the same time I was doing the form submit and there nothing to check that settings from the backend were received from socketio before starting to upload it.

So the chunksize option was undefined.

**Comment by rico345100** [comment]
Well, I didn't thought that sends a file with just initialized condition, that could be a problem. Thanks for reporting this issue and I will add some morr features to prevent that.

**Comment by rico345100** [comment]
Hey, I just updated my code to added new event "ready". I added both client and server side, but in this case, you need to update your client side code. But you have to update both manually just with:

```bash
$ npm update --save socket.io-file socket.io-file-client
```

After that, you can now use ready event.
```
var uploader = new SocketIOFileClient(socket);
uploader.on('ready', function() {
    console.log('Send file from here!');
});
```

**Comment by patarapolw** [comment]
> Hey, I just updated my code to added new event "ready". I added both client and server side, but in this case, you need to update your client side code. But you have to update both manually just with:
> 
> ```shell
> $ npm update --save socket.io-file socket.io-file-client
> ```
> 
> After that, you can now use ready event.
> 
> ```
> var uploader = new SocketIOFileClient(socket);
> uploader.on('ready', function() {
>     console.log('Send file from here!');
> });
> ```

Should update the documentation on the client-side.
