### ISSUE TITLE
Renaming File On Sever Before Writing

### ISSUE THREAD

**Issue by dazamate** [rico345100/socket.io-file#32]
I can't figure out how to rename the file on the server side before your library creates the file and starts writing.

        `const uploader = new SocketIOFile(socket, {
		uploadDir: settings.uploadPath,				// simple directory
		maxFileSize: 4194304, 						// 4 MB. default is undefined(no limit)
		chunkSize: 10240,							// default is 10240(1KB)
		transmissionDelay: 0,						
		overwrite: true 							// overwrite file if exists, default is true.
	});
	
	uploader.on('start', (fileInfo) => {
		let saveAs = fileInfo.name;
		let count = 1;
		
		const name = fileInfo.name.split('.').slice(0, -1).join('.'); // Name of file
		const ext = fileInfo.name.split('.').pop(); // extension of file
		
		// if duplicate name was uploaded, add unique suffix
		while( fs.existsSync(`${settings.uploadPath}/${saveAs}`) ) {			
			saveAs = `${name}-${count}.${ext}`;
			count++;
		}
		
		// Somehow override the filename to be saved
		fileInfo.name = saveAs;	
		console.log(`saving as ${saveAs}`);
			
		console.log('Start uploading');
		console.log(fileInfo);
	});`

renaming the filename in the fileInfo object passed doesn't have an effect.

Is there anyway to do this with your library? Thank you.

**Comment by rico345100** [comment]
Hi there!
start event will trigger right before uploading the file, so that's not proper position to rename it. I would recommend you to do that after upload finish, like 'complete' event.

Also from 2.0.1, you can easily rename it with rename option.

```javascript
var path = require('path');
var count = 0;

var uploader = new SocketIOFile(socket, {
	overwrite: false,
	rename: function(filename, fileInfo) {
		var file = path.parse(filename);
	        var fname = file.name;
        	var ext = file.ext;
		return `${fname}_${count++}.${ext}`;
	}
);
```

**Comment by dazamate** [comment]
Thank you Rico

Does the rename function get called before or after the file is written?

I am just trying to check if a file exists with the same name on the server before any writing is done, and writing to a diff file name so the original file doesn't get overwritten.

**Comment by rico345100** [comment]
Rename property is used when creating a new file. If there is a file that has the same name, it just finishes the upload, unless you set the overwrite = true.

**Comment by dazamate** [comment]
So this partially works but we cant see the new filename in the 'complete' event.

        `const uploader = new SocketIOFile(socket, {
		uploadDir: settings.uploadPath,				// simple directory
		maxFileSize: 4194304, 						// 4 MB. default is undefined(no limit)
		chunkSize: 10240,							// default is 10240(1KB)
		transmissionDelay: 0,						
		overwrite: false, 							// overwrite file if exists, default is true.
		rename: (filename, fileInfo) => {
			return renameFile(filename, fileInfo);
		}
	 });
	
	function renameFile(filename, fileInfo) {
		let saveAs = filename;
		let count = 1;
		
		const name = filename.split('.').slice(0, -1).join('.'); // Name of file
		const ext = filename.split('.').pop(); // extension of file
		
		// if duplicate name was uploaded, add unique suffix
		while( fs.existsSync(`${settings.uploadPath}/${saveAs}`) ) {			
			saveAs = `${name}-${count}.${ext}`;
			count++;
		}
		
		// Somehow override the filename to be saved
		console.log(`Unused file name found: ${saveAs}`);
		fileInfo.name = filename;
		return filename;
	}

	uploader.on('complete', (fileInfo) => {
		console.log('Upload Complete.');
		onFileUploadComplete(socket, fileInfo);				
	});`


See console log here
https://i.imgur.com/2AnJJEM.png

I know I can probably make a work around using globals but that is messy :)

**Comment by dazamate** [comment]
Thank you very much. That solved the issue.
