### ISSUE TITLE
this.rename is not a function

### ISSUE THREAD

**Issue by jfmmm** [rico345100/socket.io-file#4]
There a bug when you use the rename option.

```
TypeError: this.rename is not a function
    at Socket.<anonymous> (/Users/username/Documents/projects/projectName/node_modules/socket.io-file/index.js:91:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at /Users/username/Documents/projects/projectName/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rico345100** [comment]
Hi, jfmmm. rename is available after v2.0.1, so please check your current version of socket.io-file. Or if you already using it, could you paste your code that using or related with Socket.io-file? It is hard to figuring out what is the problem without specific details :)

**Comment by jfmmm** [comment]
Yeah no I have 2.0.1, but I found why..

I just assumed that I could just pass a string to the rename option like `rename: "myNewFilename.xls"`.. didn't realize it had to be a function.

**Comment by rico345100** [comment]
Oh, I didn't thought about that passing new filename directly. I will add plain string support for rename option.

**Comment by rico345100** [comment]
Hey :) I just updated to support string rename option. Make sure update Socket.io-file to latest version! Thanks!
