### ISSUE TITLE
Don't expose server path to browser client

### ISSUE THREAD

**Issue by TroyWolf** [rico345100/socket.io-file#5]
When a file upload completes, the emitObj is sent back to the client.
`let emitObj = {
    name: filename,
    size: uploadingFiles[id].size,
    wrote: uploadingFiles[id].wrote,
    uploadDir: uploadingFiles[id].uploadDir,
    mime: mimeType,
    estimated: endTime - startTime
};`

This object includes "uploadDir", which exposes my "secret" server path to my web users.

**Comment by rico345100** [comment]
Socket.io-file supports multiple path to upload, so that's why it returns uploadDir to the client. But I think that you are right, so I'll remove the uploaded path from client, means server's oncomplete will still get it because someone might be needed. Thank you for opinion :)

**Comment by rico345100** [comment]
It's done. Don't forget to update to socket.io-file - v2.0.14!

**Comment by TroyWolf** [comment]
Excellent! Thank you!

**Comment by rico345100** [comment]
No problemo! Don't forget give me a star! XD
